Cimpl 6 fix
standardhealth/shr-grammar pull request #36
Opened 2019-02-21 16:11 UTC by AmartC

2019-02-21 16:18 UTC, cmoesel requested changes
I don't have a problem with the changes, but there are git conflicts you must resolve first before we can merge.

2019-03-06 20:41 UTC, AmartC commented
I resolved the Git issue so this commit is ready to be merged now.

2019-03-06 20:44 UTC, cmoesel approved these changes

2019-03-06 20:44 UTC, merged

2019-03-06 20:45 UTC, cmoesel commented
I squash-merged it to combine the commits and merge commits into one (and keep history cleaner).